name: AIRAC-update

on:
  schedule:
    - cron: "0 1 * * *"
  # manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: initialise
        run: |
          echo repo=$GITHUB_REPOSITORY	 available in $GITHUB_WORKSPACE event=$GITHUB_EVENT_NAME
          ls -l .
          git log --graph --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit
      - name: download public files
        run: |
          wget --non-verbose -P tmp https://opensky-network.org/datasets/metadata/doc8643AircraftTypes.csv
          wget --non-verbose -P tmp https://opensky-network.org/datasets/metadata/doc8643Manufacturers.csv
          wget --non-verbose -P tmp https://opensky-network.org/datasets/metadata/aircraftDatabase.csv
          rsync -av tmp/*.csv src/
          ls -l src
          
      - name: add files to repository
        run: |
          git status
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@nomail.com
          git add src/*
          git commit -m "AIRAC update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
