name: AIRAC-update

on:
  # manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: ls -l $GITHUB_WORKSPACE
      - name: Create a file
        working-directory: $GITHUB_WORKSPACE
        run: |
          pwd
          touch test.txt
          ls -l

      - name: Run a multi-line script
        run: |
          git status
          git log
