name: AIRAC-update

on:
  # runs every Thursday night to cover 28 day AIRAC update
  schedule:
    - cron: "0 1 * * THU"
  # manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: initialise
        run: |
          echo repo=$GITHUB_REPOSITORY	 available in $GITHUB_WORKSPACE event=$GITHUB_EVENT_NAME
          ls -l .
          git log --graph --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit
      - name: calculate AIRAC date
        run: echo "AIRACDATE=$(expr $(date +\%s) / 86400 % 28 )" >> $GITHUB_ENV
        shell: bash
      - name: test if AIRAC date
        if: env.AIRACDATE != 0
        run: echo "Today is not an AIRAC date"
      - name: download public files
        if: env.AIRACDATE == 0
        run: |
          wget --no-verbose -P tmp https://opensky-network.org/datasets/metadata/doc8643AircraftTypes.csv
          wget --no-verbose -P tmp https://opensky-network.org/datasets/metadata/doc8643Manufacturers.csv
          wget --no-verbose -P tmp https://opensky-network.org/datasets/metadata/aircraftDatabase.csv
          
          wget --no-verbose -O - https://data.flightairmap.com/data/routes.tsv.gz | gunzip -c > tmp/routes.tsv
          tail -n +2 tmp/routes.tsv | awk 'BEGIN {OFS = ","} $1~/^[A-Z]{3}[0-9]/ && $3~/^[A-Z]{4}$/ && $5~/^[A-Z]{4}$/ {print $1,$3,$5}' | sort > tmp/routes.csv

          rsync -av tmp/*.csv src/
          ls -l src
          
      - name: add files to repository
        if: env.AIRACDATE == 0
        run: |
          git status
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@nomail.com
          git add src/*
          git commit -m "AIRAC update" -a

      - name: Push changes
        if: env.AIRACDATE == 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
