name: AIRAC-update

on:
  # manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: display repo dir location
        run: |
          echo repo=$GITHUB_REPOSITORY	 available in $GITHUB_WORKSPACE event=$GITHUB_EVENT_NAME
          ls -l $GITHUB_WORKSPACE
          touch test.txt
          ls -l .
          git status
