name: AIRAC-update

on:
  # manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: display repo dir location
        run: echo $GITHUB_WORKSPACE


